"""
OpenTune YouTube Music API Python Package.
Rewritten from OpenTune Android App (InnerTube API).
"""

from mimitune.models import (
    YouTubeLocale,
    PlaybackAuthState,
    YouTubeClientPreset,
    WEB,
    WEB_REMIX,
    ANDROID_MUSIC,
    TVHTML5,
    Artist,
    SongItem,
    AlbumItem,
    ArtistItem,
    PlaylistItem,
    SearchSummary,
    SearchSummaryPage,
    SearchResult,
    AlbumPage,
    ArtistSection,
    ArtistPage,
    ArtistItemsPage,
    PlaylistPage,
    HomePage,
    ExplorePage,
    ChartSection,
    ChartsPage,
    LibraryPage,
    HistorySection,
    HistoryPage,
    AccountInfo,
    MediaInfo,
    TranscriptCue,
    NextResult,
    PlayerResponse,
)
from mimitune.client import InnerTubeClient
from mimitune.api import YTMusic

__all__ = [
    "YouTubeLocale",
    "PlaybackAuthState",
    "YouTubeClientPreset",
    "WEB",
    "WEB_REMIX",
    "ANDROID_MUSIC",
    "TVHTML5",
    "Artist",
    "SongItem",
    "AlbumItem",
    "ArtistItem",
    "PlaylistItem",
    "SearchSummary",
    "SearchSummaryPage",
    "SearchResult",
    "AlbumPage",
    "ArtistSection",
    "ArtistPage",
    "ArtistItemsPage",
    "PlaylistPage",
    "HomePage",
    "ExplorePage",
    "ChartSection",
    "ChartsPage",
    "LibraryPage",
    "HistorySection",
    "HistoryPage",
    "AccountInfo",
    "MediaInfo",
    "TranscriptCue",
    "NextResult",
    "PlayerResponse",
    "InnerTubeClient",
    "YTMusic",
]

__version__ = "0.1.0"
